name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Cache CMake Dependencies (FetchContent)
      uses: actions/cache@v4
      with:
        path: build/_deps
        key: ${{ runner.os }}-cmake-deps-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ runner.os }}-cmake-deps-

    - name: Configure CMake
      run: cmake -B build

    - name: Build Project
      run: cmake --build build --config Debug

    - name: Install OpenCppCoverage
      shell: bash
      run: |
        curl -L https://github.com/OpenCppCoverage/OpenCppCoverage/releases/download/release-0.9.9.0/OpenCppCoverageSetup-x64-0.9.9.0.exe -o setup.exe
        ./setup.exe /VERYSILENT
        echo "C:/Program Files/OpenCppCoverage" >> $GITHUB_PATH

    - name: Run Tests with Coverage
      working-directory: build
      run: OpenCppCoverage.exe --sources My2DEngine --export_type cobertura:coverage.xml -- ctest -C Debug --output-on-failure

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage
        path: build/coverage.xml
